# Generated by Django 5.2 on 2025-05-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulink',
            old_name='url_orpath',
            new_name='url_or_path',
        ),
    ]
