# Generated by Django 5.2 on 2025-06-27 10:51

import utils.models_validadors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_setup", "0005_sitesetup_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetup",
            name="favicon",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="assets/favicon/%Y/%m/",
                validators=[utils.models_validadors.validate_png],
            ),
        ),
    ]
